@startuml seq

title

=Sequence diagram for determine student identification

end title



activate User
User -> Application: Type ID, password of\nGachon University homepage

activate Application
Application -> Server: Send request

activate Server
Server -> "Gachon Univ. Homepage": Make LogIn request\n(ID, password)

alt Login Success
    activate "Gachon Univ. Homepage"
    "Gachon Univ. Homepage" -->> Server: Respond homepage
    activate Server
    Server -->> Application: Send message\n"Validity approved"
    Server -->> Server: Discard\n(ID, password)
    deactivate Server
    Application -->> User: Send message: Login fail
    
else Login fail
    "Gachon Univ. Homepage" -->> Server: Respond error page
    deactivate "Gachon Univ. Homepage"
    activate Server
    Server -->> Application: Send message\n"Invalid account"
    Server -->> Server: Discard\n(ID, password)
    deactivate Server
    deactivate Server
    Application -->> User: Send message: Login success
    deactivate Application
end

deactivate User


@enduml