@startuml

start
:Request Classroom data;
:Get Classroom data;
:Request reservation;

:Update DB;
if (timeout) then
  :Update DB;
elseif (Request checkout) then
  :Update DB;
else (nothing)
endif;
stop
@enduml