@startuml sequence

activate ADMIN

ADMIN ->> SERVER: **펌웨어 파일 전송**
activate SERVER
SERVER -> SERVER: 펌웨어 파일 업로드
deactivate SERVER

ADMIN ->> SERVER : **GET:/v/check**\nbody -> 태그 정보\n · DEVICE_SERIES\n · BLEProvider.data[BLEProtocol.version]\n · other TAGs
activate SERVER
SERVER ->> SERVER: 태그 정보 획득
deactivate SERVER

ADMIN ->> SERVER: 업로드 버튼 클릭
activate SERVER

SERVER -> SERVER : update(...args)\n · 파일 이름\n · 파일 경로\n태그 정보
activate SERVER
note over SERVER : 데이터베이스 INSERT
SERVER -> SERVER : 정상 처리 여부\n(중복 및 유효하지 않은 값 등)
deactivate SERVER
alt TRUE
    SERVER -> ADMIN : TRUE
else FALSE
    
    SERVER -> ADMIN :  FALSE
    deactivate SERVER
end

<<- ADMIN : 메시지 표출
deactivate ADMIN

@enduml